### ISSUE TITLE
Nye oprettede rapporter er ikke med i audittrail

### ISSUE THREAD

**Issue by rasmuserik** [solsort/fmtools#72]
Rapport oprettet  2016-07-30T11:22:41.397, men ingen events i audittrail efter 2016-07-24T15:40:02.223

https://fmtools.solsort.com/api/v1/AuditTrail?trailsAfter=2016-07-24T15:40:02.223:

``` json
{"Manifest":{"FetchTime":6,"Result":1,"Message":""},"AuditTrails":[]}
```

Rapporten:

``` json
{
  "Manifest": {
    "FetchTime": 13,
    "Result": 1,
    "Message": ""
  },
  "ReportTable": {
    "ReportGuid": "f034ac26-2cdf-4aad-a41e-4ac5af9b94ad",
    "ObjectId": 444,
    "TemplateGuid": "049c8166-dafc-470a-b90a-73cd6a067b3c",
    "ReportType": "Hovedstation",
    "ReportName": "hc",
    "CreatedDate": "2016-07-30T11:22:41.397",
    "CreatedBy": 164,
    "CompletedDate": "1753-01-01T00:00:00",
    "StatusTypeGuid": "f74a5e2a-5a46-4fa1-aae6-c659ce97405d",
    "LastUpdatedBy": 164,
    "LastUpdatedAt": "2016-07-30T11:22:41.397",
    "AssignedTo": null,
    "ReportCategory": 1,
    "ReportParts": [],
    "ReportFields": [],
    "ReportFiles": []
  }
}
```

**Comment by repzak** [comment]
Fejl rettet, og jeg kunne også se at der var samme problem for afslut rapport, så det har jeg også rettet med det samme.

Løsningen er at der er kommet en ny AuditTrail type 'Report' med Id 19, som betyder at App'en skal opfriske de åbne rapporter den kender til, via http://app.fmtools.dk/Help/Api/GET-api-v1-Report

Hvis det er App'en der opretter eller afslutter en rapport, er det så tanken at det audit trail guid der kommer med tilbage, kan bruges til se bort fra netop denne 'hændelse' når den fulde AuditTrail liste kaldes.

**Comment by rasmuserik** [comment]
Tror at den er løst, men kan ikke verificere pga. #77

**Comment by rasmuserik** [comment]
Virker.
